/*
 * NVIC_priority.h
 *
 *  Created on: Mar 17, 2024
 *      Author: matto
 */

#ifndef NVIC_FREERTOS_PRIORITIES_H_
#define NVIC_FREERTOS_PRIORITIES_H_

#include "stm32f4xx.h"

#define PRIORITY__MAX_MATCHED SET
#define PRIORITY_OUT_OF_LIMIT RESET

enum NVIC_RTOS{
	e_PRIORITY_FREERTOS_MIN_IDLE = 0,
	e_PRIORITY_FREERTOS_MIN_PLUS_1,
	e_PRIORITY_FREERTOS_MIN_PLUS_2,
	e_PRIORITY_FREERTOS_MIN_PLUS_3,
	e_PRIORITY_FREERTOS_MIN_PLUS_4,
	e_PRIORITY_FREERTOS_MIN_PLUS_5,
	e_PRIORITY_FREERTOS_MIN_PLUS_6,
	e_PRIORITY_FREERTOS_MIN_PLUS_7,
	e_PRIORITY_FREERTOS_MIN_PLUS_8,
	e_PRIORITY_FREERTOS_MIN_PLUS_9,
	e_PRIORITY_FREERTOS_MIN_PLUS_10,
	e_PRIORITY_FREERTOS_MIN_PLUS_11,
	e_PRIORITY_FREERTOS_MIN_PLUS_12,
	e_PRIORITY_FREERTOS_MIN_PLUS_13,
	e_PRIORITY_FREERTOS_MIN_PLUS_14,
	e_PRIORITY_FREERTOS_MIN_PLUS_15_MAX
};

enum NVIC_NORMAL{
	e_PRIORITY_NORMAL_MIN_PLUS_15_MAX = 0,
	e_PRIORITY_NORMAL_MIN_PLUS_14,
	e_PRIORITY_NORMAL_MIN_PLUS_13,
	e_PRIORITY_NORMAL_MIN_PLUS_12,
	e_PRIORITY_NORMAL_MIN_PLUS_11,
	e_PRIORITY_NORMAL_MIN_PLUS_10,
	e_PRIORITY_NORMAL_MIN_PLUS_9,
	e_PRIORITY_NORMAL_MIN_PLUS_8,
	e_PRIORITY_NORMAL_MIN_PLUS_7,
	e_PRIORITY_NORMAL_MIN_PLUS_6,
	e_PRIORITY_NORMAL_MIN_PLUS_5,
	e_PRIORITY_NORMAL_MIN_PLUS_4,
	e_PRIORITY_NORMAL_MIN_PLUS_3,
	e_PRIORITY_NORMAL_MIN_PLUS_2,
	e_PRIORITY_NORMAL_MIN_PLUS_1,
	e_PRIORITY_NORMAL_MIN
};

#endif /* NVIC_FREERTOS_PRIORITIES_H_ */
